version: "3.9"

services:
  db:
    image: postgres:16
    container_name: mgp-postgres
    environment:
      POSTGRES_USER: mgp
      POSTGRES_PASSWORD: mgp
      POSTGRES_DB: mgp_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
